/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hello */
        get: operations["hello_api_hello_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sse-schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE event schema (for documentation / codegen)
         * @description Returns the StreamEvent structure used in SSE streams. Not a real endpoint.
         */
        get: operations["sse_schema_api_sse_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Workspace */
        post: operations["set_workspace_api_workspace_set_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Sessions */
        get: operations["list_all_sessions_api_sessions_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_session__sid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/{sid}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_api_session__sid__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/{sid}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Status
         * @description Return status for one session plus global runtime busy state.
         */
        get: operations["session_status_api_session__sid__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runtime Status
         * @description Lightweight check: is any runtime currently busy?
         */
        get: operations["runtime_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/{sid}/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recover Session
         * @description Return full session state for frontend recovery after refresh.
         */
        get: operations["recover_session_api_session__sid__recover_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/{sid}/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Commits
         * @description Return all shadow commits for this workspace.
         */
        get: operations["list_commits_api_session__sid__commits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/{sid}/commits/{sha}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Commit
         * @description Return metadata for a specific commit.
         */
        get: operations["get_commit_api_session__sid__commits__sha__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/{sid}/workspace/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Commit
         * @description Restore workspace to a shadow commit without modifying messages.
         */
        post: operations["restore_commit_api_session__sid__workspace_restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/{sid}/messages/truncate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Truncate Messages
         * @description Truncate message history without modifying workspace commits.
         */
        post: operations["truncate_messages_api_session__sid__messages_truncate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/{sid}/interrupt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interrupt Session
         * @description Interrupt the running agent loop for this session.
         */
        post: operations["interrupt_session_api_session__sid__interrupt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interrupt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interrupt Global
         * @description Interrupt whatever session is currently running (no session ID needed).
         */
        post: operations["interrupt_global_api_interrupt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skills */
        get: operations["list_skills_api_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/session-defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Settings */
        get: operations["get_session_settings_api_settings_session_defaults_get"];
        /** Update Session Settings */
        put: operations["update_session_settings_api_settings_session_defaults_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/session-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Session Rule */
        post: operations["add_session_rule_api_settings_session_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/session-rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Session Rule */
        delete: operations["delete_session_rule_api_settings_session_rules__rule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/{sid}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Start a chat turn and return its SSE stream.
         */
        post: operations["chat_api_session__sid__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/{sid}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description SSE reconnect. Replay persisted messages, then subscribe to live events.
         */
        get: operations["stream_events_api_session__sid__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/{sid}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Respond */
        post: operations["respond_api_session__sid__respond_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/llm/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Llm Calls */
        get: operations["list_llm_calls_api_metrics_llm_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/llm/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Llm Summary */
        get: operations["get_llm_summary_api_metrics_llm_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/llm/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Llm Dashboard */
        get: operations["get_llm_dashboard_api_metrics_llm_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memories */
        get: operations["list_memories_api_memory_get"];
        put?: never;
        /** Add Memory */
        post: operations["add_memory_api_memory_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Memory */
        delete: operations["delete_memory_api_memory__memory_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddMemoryRequest */
        AddMemoryRequest: {
            /** Content */
            content: string;
            /**
             * Kind
             * @default fact
             */
            kind: string;
        };
        /** AddRuleRequest */
        AddRuleRequest: {
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Question
             * @description Question or task for the agent
             */
            question: string;
            /**
             * Max Steps
             * @description Max reasoning steps
             * @default 100
             */
            max_steps: number;
        };
        /** CommitDetail */
        CommitDetail: {
            /** Sha */
            sha: string;
            /** Short Sha */
            short_sha: string;
            /** Message */
            message: string;
            /** Author Time */
            author_time: number;
            /** Files */
            files: string[];
        };
        /** CommitInfo */
        CommitInfo: {
            /** Sha */
            sha: string;
            /** Short Sha */
            short_sha: string;
            /** Message */
            message: string;
            /** Author Time */
            author_time: number;
        };
        /** CommitsResponse */
        CommitsResponse: {
            /** Commits */
            commits: components["schemas"]["CommitInfo"][];
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Preamble
             * @default
             */
            preamble: string;
            /** Rules */
            rules?: string[];
            /** Preloaded Skills */
            preloaded_skills?: string[];
            /**
             * Tool Set Preset
             * @default all
             */
            tool_set_preset?: components["schemas"]["ToolSetPreset"];
            /** Custom Tools */
            custom_tools?: string[];
        };
        /** CreateSessionResponse */
        CreateSessionResponse: {
            /** Session Id */
            session_id: string;
            /** Workspace */
            workspace: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Session */
            session: {
                [key: string]: unknown;
            };
            /** History */
            history: components["schemas"]["Message"][];
        };
        /** InterruptResponse */
        InterruptResponse: {
            /** Ok */
            ok: boolean;
        };
        /** ListSessionsResponse */
        ListSessionsResponse: {
            /** Workspace */
            workspace: string;
            /** Sessions */
            sessions: {
                [key: string]: unknown;
            }[];
        };
        /**
         * Message
         * @description 贯穿流式缓冲 / 持久化 / 渲染的唯一消息类型。
         *
         *     后端流式构建时直接 append 字段，完成后 model_dump() 落盘；
         *     前端收到 StreamEvent 后直接 msg[field] += delta 镜像构建。
         */
        Message: {
            /** Id */
            id: string;
            /** Turn Id */
            turn_id: string;
            /** @default assistant */
            role: components["schemas"]["MessageRole"];
            /** @default streaming */
            status: components["schemas"]["MessageStatus"];
            /**
             * Content
             * @default
             */
            content: string;
            /**
             * Reasoning
             * @default
             */
            reasoning: string;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCall"][];
            /**
             * Tool Result
             * @default
             */
            tool_result: string;
            /**
             * Tool Call Id
             * @default
             */
            tool_call_id: string;
            /**
             * Tool Name
             * @default
             */
            tool_name: string;
            /**
             * Error
             * @default
             */
            error: string;
        };
        /**
         * MessageRole
         * @description 消息角色。USER/TOOL 天然 COMPLETE，ASSISTANT 从 STREAMING 开始。
         * @enum {string}
         */
        MessageRole: "user" | "assistant" | "tool";
        /**
         * MessageStatus
         * @description 消息构建状态。
         * @enum {string}
         */
        MessageStatus: "streaming" | "complete";
        /** MessageTruncateRequest */
        MessageTruncateRequest: {
            /** Message Id */
            message_id: string;
            /**
             * Keep
             * @default false
             */
            keep: boolean;
        };
        /** MessageTruncateResponse */
        MessageTruncateResponse: {
            /** Ok */
            ok: boolean;
            /** Message Id */
            message_id: string;
            /**
             * Removed
             * @default 0
             */
            removed: number;
            /**
             * Deleted Subagents
             * @default 0
             */
            deleted_subagents: number;
        };
        /** RecoverResponse */
        RecoverResponse: {
            /** Session */
            session: {
                [key: string]: unknown;
            };
            /** Messages */
            messages: components["schemas"]["Message"][];
            /**
             * Session Running
             * @default false
             */
            session_running: boolean;
            /**
             * Runtime Busy
             * @default false
             */
            runtime_busy: boolean;
            current_message?: components["schemas"]["Message"] | null;
            pending_request?: {
                [key: string]: unknown;
            } | null;
        };
        /** RespondRequest */
        RespondRequest: {
            /**
             * Message Id
             * @description Message ID to respond to
             */
            message_id: string;
            /**
             * Response
             * @description User response payload
             */
            response: {
                [key: string]: unknown;
            };
        };
        /** RuntimeStatusResponse */
        RuntimeStatusResponse: {
            /** Runtime Busy */
            runtime_busy: boolean;
        };
        /** SessionRule */
        SessionRule: {
            /** Id */
            id: string;
            /** Content */
            content: string;
        };
        /** SessionSettings */
        SessionSettings: {
            /**
             * Preamble
             * @default
             */
            preamble: string;
            /** Rules */
            rules?: components["schemas"]["SessionRule"][];
            /** Default Rule Ids */
            default_rule_ids?: string[];
            /** Default Skill Names */
            default_skill_names?: string[];
        };
        /** SessionStatusResponse */
        SessionStatusResponse: {
            /** Session Running */
            session_running: boolean;
            /** Runtime Busy */
            runtime_busy: boolean;
        };
        /** SetWorkspaceRequest */
        SetWorkspaceRequest: {
            /**
             * Path
             * @description Absolute or relative path to new workspace
             */
            path: string;
        };
        /** SkillInfoResponse */
        SkillInfoResponse: {
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** SkillListResponse */
        SkillListResponse: {
            /** Skills */
            skills: components["schemas"]["SkillInfoResponse"][];
        };
        /** ToolInfoResponse */
        ToolInfoResponse: {
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** ToolPresetListResponse */
        ToolPresetListResponse: {
            /** Presets */
            presets: components["schemas"]["ToolPresetResponse"][];
            /** Tools */
            tools: components["schemas"]["ToolInfoResponse"][];
        };
        /** ToolPresetResponse */
        ToolPresetResponse: {
            /** Name */
            name: components["schemas"]["ToolSetPreset"];
            /** Tools */
            tools: string[];
        };
        /**
         * ToolSetPreset
         * @description 可用工具集预设。
         *
         *     对标 Rust ToolSet enum:
         *     - ALL: 全部工具
         *     - MINIMAL: read_file, write, glob, grep
         *     - CODE_ONLY: read_file, write, edit, glob, grep, shell
         *     - REVIEW_ONLY: read_file, glob, grep
         *     - CUSTOM: 用户指定
         * @enum {string}
         */
        ToolSetPreset: "all" | "minimal" | "code_only" | "review_only" | "custom";
        /**
         * StreamEventKind
         * @description SSE 事件种类。
         * @enum {string}
         */
        StreamEventKind: "message_start" | "chunk_delta" | "chunk_complete" | "message_finish" | "turn_complete" | "interrupted" | "guard_request";
        /**
         * StreamEventSchema
         * @description SSE event structure — documented for frontend gen, served via SSE not REST.
         */
        StreamEventSchema: {
            kind: components["schemas"]["StreamEventKind"];
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Message Id
             * @default
             */
            message_id: string;
            /**
             * Turn Id
             * @default
             */
            turn_id: string;
            /**
             * Field
             * @default
             */
            field: string;
            /**
             * Delta
             * @default
             */
            delta: string;
            /**
             * Full Content
             * @default
             */
            full_content: string;
            /**
             * Tool Name
             * @default
             */
            tool_name: string;
            /**
             * Tool Args
             * @default
             */
            tool_args: string;
            /**
             * Is Error
             * @default false
             */
            is_error: boolean;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /**
         * ToolCall
         * @description OpenAI-format tool call。
         */
        ToolCall: {
            /**
             * Id
             * @default
             */
            id: string;
            /**
             * Type
             * @default function
             */
            type: string;
            function?: components["schemas"]["ToolCallFunction"];
        };
        /**
         * ToolCallFunction
         * @description OpenAI-format function 字段。
         */
        ToolCallFunction: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Arguments
             * @default
             */
            arguments: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkspaceRestoreRequest */
        WorkspaceRestoreRequest: {
            /** Commit Sha */
            commit_sha: string;
            /**
             * Set Head
             * @default true
             */
            set_head: boolean;
        };
        /** WorkspaceRestoreResponse */
        WorkspaceRestoreResponse: {
            /** Ok */
            ok: boolean;
            /** Commit Sha */
            commit_sha: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    hello_api_hello_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    sse_schema_api_sse_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamEventSchema"];
                };
            };
        };
    };
    get_workspace_api_workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    set_workspace_api_workspace_set_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSessionsResponse"];
                };
            };
        };
    };
    list_all_sessions_api_sessions_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    delete_session_api_session__sid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_session__sid__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_status_api_session__sid__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runtime_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatusResponse"];
                };
            };
        };
    };
    recover_session_api_session__sid__recover_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoverResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_commits_api_session__sid__commits_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_commit_api_session__sid__commits__sha__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
                sha: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_commit_api_session__sid__workspace_restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceRestoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceRestoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    truncate_messages_api_session__sid__messages_truncate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageTruncateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageTruncateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interrupt_session_api_session__sid__interrupt_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterruptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interrupt_global_api_interrupt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterruptResponse"];
                };
            };
        };
    };
    list_skills_api_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillListResponse"];
                };
            };
        };
    };
    get_session_settings_api_settings_session_defaults_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSettings"];
                };
            };
        };
    };
    update_session_settings_api_settings_session_defaults_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionSettings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_session_rule_api_settings_session_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRuleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_rule_api_settings_session_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_session__sid__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_session__sid__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    respond_api_session__sid__respond_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RespondRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_llm_calls_api_metrics_llm_calls_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                session_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_llm_summary_api_metrics_llm_summary_get: {
        parameters: {
            query?: {
                session_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_llm_dashboard_api_metrics_llm_dashboard_get: {
        parameters: {
            query?: {
                limit?: number;
                session_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memories_api_memory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    add_memory_api_memory_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_memory_api_memory__memory_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
