"""Scheduler — 单例执行调度器。

一个 Project 只有一个 Scheduler，一次只运行一个 Session。
每次 start() 创建新的 TranscriptStream（per-session 临时通道）。
Transcript 持久化存储在 Session 中。
"""

from __future__ import annotations

import asyncio
import uuid as _uuid

from agent.errors import InterruptedError, ToolMismatchError, repair_transcripts
from agent.metrics import LLMCallContext
from agent.sandbox import Sandbox
from agent.session import Session
from agent.shadow_repo import ShadowRepo
from agent.tools import TaskList, TaskRewrite
from agent.tools.shell import get_platform_hint
from agent.tools.skill import skill_context_message
from agent.tools.subagent import SubAgent
from agent.tools.task import task_context_message
from agent.tools.toolset import ToolSet
from agent.transcript import TranscriptStream

# ── System prompt（只定义一次）─────────────────────────────

# ⚠️  永远不要在 SYSTEM_PROMPT 中硬编码列举「非特殊」工具。
#     工具列表由 ToolSet 动态生成并通过 OpenAI tools 参数注入，
#     硬编码会导致：新增工具时提示词过时、删除工具时幻觉调用。
#     特殊工具（如 SubAgent/Task）需要额外行为指导的可以豁免。
#
# ⚠️  NEVER hardcode non-special tools in SYSTEM_PROMPT.
#     The tool list is dynamically generated by ToolSet and injected
#     via the OpenAI tools parameter. Hardcoding causes stale prompts
#     when tools are added and hallucinated calls when tools are removed.
#     Special tools (e.g. SubAgent/Task) that need extra behavioural
#     guidance are exempt.

SYSTEM_PROMPT = """\
You are an intelligent assistant capable of using external tools and following a plan.
Use the provided functions to interact with the system.

## Communication
- Be conversational but professional.
- Refer to the user in the second person and yourself in the first person.
- Format your responses in markdown. Use backticks to format file, directory, function, and class names.
- NEVER lie or make things up.
- Refrain from apologizing all the time when results are unexpected. Instead, just try your best to proceed or explain the circumstances to the user without apologizing.

## Rules
- Pick the function that best fits the current situation.
- Follow runtime context messages for platform details, available skills, and current tasks.
- Before you read or edit a file, you must first find the full path. DO NOT ever guess a file path!
- When running commands that may run indefinitely or for a long time (such as build scripts, tests, servers, or file watchers), specify `timeout_ms` to bound runtime. If the command times out, the user can always ask you to run it again with a longer timeout or no timeout if they're willing to wait or cancel manually.
- Avoid HTML entity escaping - use plain characters instead.

## Fixing Diagnostics
1. Make 1-2 attempts at fixing diagnostics, then defer to the user.
2. Never simplify code you've written just to solve diagnostics. Complete, mostly correct code is more valuable than perfect code that doesn't solve the problem.

## Debugging
When debugging, only make code changes if you are certain that you can solve the problem.
Otherwise, follow debugging best practices:
1. Address the root cause instead of the symptoms.
2. Add descriptive logging statements and error messages to track variable and code state.
3. Add test functions and statements to isolate the problem.

## Calling External APIs
1. Unless explicitly requested by the user, use the best suited external APIs and packages to solve the task. There is no need to ask the user for permission.
2. When selecting which version of an API or package to use, choose one that is compatible with the user's dependency management file(s). If no such file exists or if the package is not present, use the latest version that is in your training data.
3. If an external API requires an API Key, be sure to point this out to the user. Adhere to best security practices (e.g. DO NOT hardcode an API key in a place where it can be exposed)
"""


def _default_toolset() -> ToolSet:
    from agent.tools import get_all_tool_classes as _all

    return ToolSet(_all())


# ── Internal helpers ──────────────────────────────────────


async def _apply_repairs(session: Session, channel: TranscriptStream, *stages) -> None:
    """运行修复管线，将新增的 repair transcript 通过 SSE 推送并增量持久化。"""
    old = session._transcripts
    repaired = repair_transcripts(old, *stages)
    new = repaired[len(old) :]
    for rt in new:
        try:
            flushed = await channel.flush(rt.id, rt.kind, base=rt.message)
            session.add_transcript(
                flushed.kind, flushed.message, flushed.id, flushed.commit_sha
            )
        except Exception:
            pass


# ============================================================
# Scheduler
# ============================================================


class Scheduler:
    """Per-Project 执行调度器（单例）。

    一次只允许一个 Session 在运行。
    TranscriptStream 是 per-execution 的临时通道。
    """

    def __init__(self) -> None:
        self._state: str = "idle"
        self._loop_task: asyncio.Task | None = None
        self._pending: dict[str, dict] = {}
        self._current_session: Session | None = None
        self._current_channel: TranscriptStream | None = None
        self._shadow_repo: ShadowRepo | None = None
        self._interrupt_event: asyncio.Event | None = None

    # ── public ────────────────────────────────────────────

    @property
    def channel(self) -> TranscriptStream | None:
        """当前运行中 session 的临时通道。"""
        return self._current_channel

    @property
    def state(self) -> str:
        return self._state

    @property
    def pending_request(self) -> dict | None:
        if self._state != "awaiting_input":
            return None
        # 返回第一个待处理请求
        for tid, pending in self._pending.items():
            return {
                "transcript_id": tid,
                "kind": pending.get("kind", "permission_request"),
                "message": pending.get("message", {}),
            }
        return None

    def is_running_session(self, session_id: str) -> bool:
        return (
            self._state != "idle"
            and self._current_session is not None
            and self._current_session.session_id == session_id
        )

    def start(
        self,
        session: Session,
        question: str,
        channel: TranscriptStream | None = None,
        max_steps: int = 50,
        shadow_repo: ShadowRepo | None = None,
    ) -> str:
        """启动 session 执行。可传入外部创建的 channel（subscribe-before-start 模式）。"""
        if self._state != "idle":
            raise RuntimeError(f"Scheduler already running (state={self._state})")
        self._current_session = session
        self._current_channel = channel if channel is not None else TranscriptStream()
        self._shadow_repo = shadow_repo
        self._interrupt_event = asyncio.Event()
        self._state = "running"
        self._loop_task = asyncio.create_task(
            self._query_loop(question, max_steps),
            name="sched",
        )
        return session.session_id

    def resolve(self, transcript_id: str, response: dict) -> None:
        """响应待处理的权限请求。"""
        pending = self._pending.get(transcript_id)
        if pending is None:
            raise KeyError(f"No pending request: {transcript_id}")
        pending["response"] = response
        pending["event"].set()

    async def interrupt(self) -> bool:
        """Signal the running query loop to stop and WAIT for full shutdown.

        Blocks until the entire execution tree (LLM, tools, SubAgents) has
        finished, transcripts are repaired, and the channel is closed.
        Returns True if a loop was running.
        """
        if self._interrupt_event is None:
            return False
        self._interrupt_event.set()
        task = self._loop_task
        if task is not None:
            try:
                await task
            except Exception:
                pass  # exceptions already handled by _on_done
        return True

    # ============================================================
    # query loop
    # ============================================================

    async def _query_loop(self, question: str, max_steps: int) -> None:
        session = self._current_session
        channel = self._current_channel
        assert session is not None and channel is not None

        try:
            # ── 1. snapshot: first turn → before; every turn → after LLM ─
            is_first = (
                self._shadow_repo is not None
                and len(self._shadow_repo.list_commits(session.session_id)) == 0
            )
            user_id = _uuid.uuid4().hex
            commit_sha = ""
            if is_first and self._shadow_repo is not None:
                try:
                    self._shadow_repo.snapshot(
                        session.session_id,
                        "Initial workspace state",
                        transcript_id="__init__",
                    )
                except Exception:
                    pass

            # ── 2. save user question transcript ─────────
            user_msg = {"role": "user", "content": question}
            t = await channel.flush(
                user_id, "user_question", base=user_msg, commit_sha=""
            )
            session.add_transcript(t.kind, t.message, t.id, commit_sha="")

            for _ in range(max_steps):
                # ── interrupt check ─────────────────
                if self._interrupt_event and self._interrupt_event.is_set():
                    raise InterruptedError("Interrupted by user")
                # ── 构建消息 ──────────────────────────
                messages: list[dict] = [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {
                        "role": "system",
                        "content": f"## Platform\n{get_platform_hint()}",
                    },
                    skill_context_message(),
                    task_context_message(session._sandbox),
                ]
                messages.extend(session.get_messages())

                # ── 模型调用（流式）────────────────────
                assistant_id = _uuid.uuid4().hex
                finish_reason = await self._model_call(
                    session,
                    channel,
                    messages,
                    session._toolset.openai_tools,
                    transcript_id=assistant_id,
                )

                # ── peek tool_calls before flush ──────
                pre_msg = channel.message
                has_tool_calls = bool(pre_msg and pre_msg.get("tool_calls"))

                # ── flush（message 由 TranscriptStream 内部构建）──
                t = await channel.flush(assistant_id, "assistant")
                session.add_transcript(t.kind, t.message, t.id)

                # ── finish_reason == "stop" → 结束 ────
                if finish_reason == "stop":
                    if self._shadow_repo is not None:
                        try:
                            sha = self._shadow_repo.snapshot(
                                session.session_id, question, transcript_id=user_id
                            )
                            aid = _uuid.uuid4().hex
                            t = await channel.flush(
                                aid,
                                "commit_attachment",
                                base={"target_tid": user_id, "commit_sha": sha},
                            )
                            session.add_transcript(t.kind, t.message, t.id)
                            for ut in reversed(session._transcripts):
                                if ut.id == user_id and ut.kind == "user_question":
                                    ut.commit_sha = sha
                                    break
                        except Exception:
                            pass
                    return

                # ── 无 tool_calls → 错误 ──────────────
                if not has_tool_calls:
                    err_id = _uuid.uuid4().hex
                    err_msg = {"message": "LLM returned no tool_calls and no content."}
                    t = await channel.flush(err_id, "error", base=err_msg)

                    session.add_transcript(t.kind, t.message, t.id)
                    return

                # ── 执行每个 tool_call ─────────────────
                for tc in t.message.get("tool_calls", []):
                    if self._interrupt_event and self._interrupt_event.is_set():
                        raise InterruptedError("Interrupted between tools")
                    await self._execute_one_tool(
                        tc, session._sandbox, session._toolset, channel
                    )
                    rid = _uuid.uuid4().hex
                    t = await channel.flush(
                        rid,
                        "tool_result",
                        base={
                            "tool_call_id": tc["id"],
                            "tool_name": tc["function"]["name"],
                            "arguments": tc["function"]["arguments"],
                        },
                    )
                    session.add_transcript(t.kind, t.message, t.id)

            # Max steps exhausted → snapshot before exit
            if self._shadow_repo is not None:
                try:
                    sha = self._shadow_repo.snapshot(
                        session.session_id, question, transcript_id=user_id
                    )
                    aid = _uuid.uuid4().hex
                    t = await channel.flush(
                        aid,
                        "commit_attachment",
                        base={"target_tid": user_id, "commit_sha": sha},
                    )
                    session.add_transcript(t.kind, t.message, t.id)
                    for ut in reversed(session._transcripts):
                        if ut.id == user_id and ut.kind == "user_question":
                            ut.commit_sha = sha
                            break
                except Exception:
                    pass

        except ToolMismatchError:
            try:
                await _apply_repairs(session, channel)
                err_id = _uuid.uuid4().hex
                err_msg = {
                    "message": "A tool call / result mismatch was detected. The conversation has been repaired. Please continue."
                }
                t = await channel.flush(err_id, "error", base=err_msg)
                session.add_transcript(t.kind, t.message, t.id)
            except Exception:
                pass
        except InterruptedError:
            try:
                await _apply_repairs(session, channel)
                err_id = _uuid.uuid4().hex
                err_msg = {
                    "message": "The user interrupted the agent before it could finish. Summarize what you have done so far and ask how to proceed."
                }
                t = await channel.flush(err_id, "error", base=err_msg)
                session.add_transcript(t.kind, t.message, t.id)
            except Exception:
                pass
        except Exception as exc:
            import traceback

            traceback.print_exc()
            try:
                await _apply_repairs(session, channel)
                err_id = _uuid.uuid4().hex
                err_msg = {"message": str(exc)}
                t = await channel.flush(err_id, "error", base=err_msg)
                session.add_transcript(t.kind, t.message, t.id)
            except Exception:
                pass
        finally:
            self._state = "idle"
            self._loop_task = None
            if self._current_channel is channel:
                channel.close()
                self._current_channel = None

    # ============================================================
    # model call
    # ============================================================

    async def _model_call(
        self,
        session: Session,
        channel: TranscriptStream,
        messages: list[dict],
        tools: list[dict],
        transcript_id: str,
    ) -> str | None:
        """流式调用 LLM，全部 chunk 进入 channel。

        message 由 TranscriptStream 在 chunk() 内部构建。
        channel 是 message 的唯一真相源——禁止在外部私自维护。
        返回 finish_reason（"stop" / "tool_calls" / None）。
        """
        finish_reason: str | None = None

        async for ev in session.llm_client.think_stream(
            messages=messages,
            tools=tools,
            metrics_context=LLMCallContext(
                session_id=session.session_id,
                transcript_id=transcript_id,
                call_type="agent_step",
            ),
        ):
            if self._interrupt_event and self._interrupt_event.is_set():
                raise InterruptedError("Interrupted during LLM call")
            if ev["kind"] == "reasoning":
                await channel.chunk(transcript_id, "thinking", ev["token"])
            elif ev["kind"] == "content":
                await channel.chunk(transcript_id, "response", ev["token"])
            elif ev["kind"] == "tool_call_chunk":
                tc = ev["tool_call"]
                idx: int = tc.get("index", 0)
                tool_id = f"{transcript_id}/tc/{idx}"

                msg = channel.ensure_open(transcript_id)
                calls = msg.setdefault("tool_calls", [])
                while len(calls) <= idx:
                    calls.append(
                        {
                            "id": "",
                            "type": "function",
                            "function": {"name": "", "arguments": ""},
                        }
                    )
                if tc.get("id"):
                    calls[idx]["id"] = tc["id"]

                fn = tc.get("function", {})
                if fn.get("name"):
                    await channel.chunk(
                        transcript_id,
                        "tool_name",
                        fn["name"],
                        chunk_id=tool_id,
                    )
                if fn.get("arguments"):
                    await channel.chunk(
                        transcript_id,
                        "tool_arguments",
                        fn["arguments"],
                        chunk_id=tool_id,
                    )
            elif ev["kind"] == "finish_reason":
                finish_reason = ev["finish_reason"]

        # Detect tool mismatch errors from the LLM
        msg = channel.message
        content = msg.get("content", "") if msg else ""
        if (
            content
            and "tool" in content.lower()
            and ("mismatch" in content.lower() or "not found" in content.lower())
        ):
            raise ToolMismatchError(content.strip())

        return finish_reason

    # ============================================================
    # tool execution
    # ============================================================

    async def _execute_one_tool(
        self,
        tc: dict,
        sandbox: object,
        toolset: object,
        channel: TranscriptStream,
    ) -> None:
        """执行单个 tool_call，结果全部通过 chunk 写入 channel。

        message 由 TranscriptStream 在 chunk() 内部构建。
        调用方从 channel.message 读取结果，自行 flush。
        """
        func_name: str = tc["function"]["name"]
        func_args: str = tc["function"]["arguments"]
        result_id = _uuid.uuid4().hex

        if self._interrupt_event and self._interrupt_event.is_set():
            raise InterruptedError("Interrupted before tool execution")

        try:
            action = toolset.parse(func_name, func_args)
        except Exception as exc:
            await channel.chunk(
                result_id,
                "tool_result",
                f"Error parsing {func_name}: {exc}",
                chunk_id=result_id,
            )
            return

        # ── Shell（流式输出）───────────────────────────
        if func_name == "Shell":
            async for chunk_text in sandbox.stream_shell(
                action.command,
                action.timeout_ms,
                interrupt_event=self._interrupt_event,
            ):
                await channel.chunk(
                    result_id, "tool_result", chunk_text, chunk_id=result_id
                )
            exit_code = sandbox.terminal._last_exit_code
            if exit_code != 0:
                await channel.chunk(
                    result_id,
                    "tool_result",
                    f"\n[exit code: {exit_code}]",
                    chunk_id=result_id,
                )
            return

        # ── SubAgent（递归子智能体）───────────────────
        if func_name == "SubAgent":
            result_str = await self._run_subagent(
                sandbox, toolset, channel, action.prompt, action.max_steps
            )
            await channel.chunk(
                result_id, "tool_result", result_str, chunk_id=result_id
            )
            return

        # ── 其他工具 ───────────────────────────────────
        try:
            result_str = await action.execute(sandbox=sandbox)
        except Exception as exc:
            result_str = f"Error: {exc}"
        await channel.chunk(result_id, "tool_result", result_str, chunk_id=result_id)

    # ============================================================
    # SubAgent
    # ============================================================

    async def _run_subagent(
        self,
        sandbox: Sandbox,
        toolset: ToolSet,
        channel: TranscriptStream,
        prompt: str,
        max_steps: int,
    ) -> str:
        """在同一个 session 内运行子智能体。

        子智能体自备静默 TranscriptStream（无 subscriber），
        _model_call 和 _execute_one_tool 的流式输出被其吸收，
        不污染主 channel。消息由静默 channel.message 读取。
        """
        subagent_tools = toolset.without(SubAgent, TaskRewrite, TaskList).openai_tools
        parent_session = self._current_session
        assert parent_session is not None

        subagent_messages: list[dict] = [
            {
                "role": "system",
                "content": (
                    "You are a sub-agent. Complete the assigned task "
                    "and return a final answer."
                ),
            },
            {"role": "user", "content": prompt},
        ]

        last_answer = ""

        for _ in range(max_steps):
            if self._interrupt_event and self._interrupt_event.is_set():
                break

            # 每轮迭代新建静默 channel，避免跨轮 message 累积
            silent = TranscriptStream()
            stream_id = _uuid.uuid4().hex

            finish_reason = await self._model_call(
                parent_session,
                silent,
                subagent_messages,
                subagent_tools,
                transcript_id=stream_id,
            )

            msg = silent.message or {}
            content = msg.get("content", "")
            tool_calls = msg.get("tool_calls", [])

            if content:
                last_answer = content

            if finish_reason == "stop" or not tool_calls:
                break

            # 添加 assistant 消息到子智能体上下文
            subagent_messages.append(
                {
                    "role": "assistant",
                    "content": content or None,
                    "tool_calls": tool_calls,
                    **(
                        {"reasoning_content": msg["reasoning_content"]}
                        if msg.get("reasoning_content")
                        else {}
                    ),
                }
            )

            # 执行工具（静默 channel 吸收流式输出，不持久化）
            for tc in tool_calls:
                if self._interrupt_event and self._interrupt_event.is_set():
                    break
                await self._execute_one_tool(
                    tc, parent_session._sandbox, parent_session._toolset, silent
                )
                result = (silent.message or {}).get("result", "")
                subagent_messages.append(
                    {
                        "role": "tool",
                        "tool_call_id": tc["id"],
                        "content": result,
                    }
                )

        return (
            f"SubAgent completed. Result: {last_answer}"
            if last_answer
            else "SubAgent completed (no output)."
        )

    # ============================================================
    # internal
    # ============================================================
